# Generated by Django 4.1.5 on 2023-01-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_play_defend_card_alter_play_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='defend_card',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='play',
            name='rule',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='play',
            name='winner',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
