# Generated by Django 4.1.5 on 2023-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_user_birth_remove_user_desc_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', '남자'), ('Female', '여자')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('Student', '학생'), ('JobSeeker', '취준생'), ('Worker', '직장인'), ('Etc', '기타')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
