# Generated by Django 4.1.5 on 2023-01-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_user_birth_user_desc_user_email_user_gender_user_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
