# Generated by Django 4.1.5 on 2023-01-19 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_user_birth_remove_user_desc_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_card', models.IntegerField()),
                ('defend_card', models.IntegerField()),
                ('accept', models.BooleanField(default=False)),
                ('winner', models.IntegerField()),
                ('rule', models.IntegerField()),
                ('attack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack', to=settings.AUTH_USER_MODEL)),
                ('defend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
