# Generated by Django 4.1.5 on 2023-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_user_score_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
